version: 2.1
orbs:
  docker: circleci/docker@2.2.0

workflows:
  commit:
    jobs:
      - docker/publish:
          deploy: true
          image: 'f512/kamulyo-pelayanan'
          use-remote-docker: true