version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy over SSH
          command: >
            ssh -o StrictHostKeyChecking=no
            ${DEPLOY_SERVER_SSH_USERNAME}@${DEPLOY_SERVER_SSH_HOST}
            ${DEPLOY_SERVER_SSH_COMMAND}

workflows:
  commit:
    jobs:
      - docker/publish:
          deploy: true
          image: f512/kamulyo-pelayanan
          tag: latest
      - deploy:
          requires:
            - docker/publish
          filters:
            branches:
              only:
                - main
