"""empty message

Revision ID: 5bbd804fdbcc
Revises: 81e8a75dd4a2
Create Date: 2023-09-30 20:38:46.460047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbd804fdbcc'
down_revision = '81e8a75dd4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dilihat_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiket', schema=None) as batch_op:
        batch_op.drop_column('dilihat_count')

    # ### end Alembic commands ###
