"""empty message

Revision ID: 81e8a75dd4a2
Revises: 
Create Date: 2023-09-26 12:52:38.331205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e8a75dd4a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_publik', sa.Boolean(), nullable=False),
    sa.Column('jenis', sa.String(length=100), nullable=False),
    sa.Column('nama_pengirim', sa.String(length=255), nullable=False),
    sa.Column('nohp_pengirim', sa.String(length=20), nullable=False),
    sa.Column('subjek', sa.String(length=255), nullable=False),
    sa.Column('narasi', sa.String(length=255), nullable=False),
    sa.Column('selesai', sa.Boolean(), nullable=False),
    sa.Column('tgl_dibuat', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=87), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('balasan_tiket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiket_id', sa.Integer(), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('tgl_dibuat', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tiket_id'], ['tiket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiket_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiket_id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tiket_id'], ['tiket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiket_attachment')
    op.drop_table('balasan_tiket')
    op.drop_table('user')
    op.drop_table('tiket')
    # ### end Alembic commands ###
