"""empty message

Revision ID: 953e6a6294a4
Revises: b22814ea036d
Create Date: 2023-10-08 15:34:23.913844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953e6a6294a4'
down_revision = 'b22814ea036d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiket', schema=None) as batch_op:
        batch_op.drop_column('nik')

    # ### end Alembic commands ###
